#!/usr/bin/env node
/**
 * Stage a release candidate: the payload, the five platform assets, SHA256SUMS,
 * both bootstraps with their identity baked in, and the reviewed record.
 *
 *   node scripts/release/stage.mjs --release v0.4.0 [--out release] [--base-url URL]
 *
 * Nothing here publishes. T14 tests these exact bytes; T15 attaches them to a
 * draft release and publishes it, and §10.3's immutability means the assets
 * cannot be repaired afterwards — so the release is assembled complete or not
 * at all.
 */
import { execFileSync } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { prepareReleaseOutput } from "./output.mjs";
import { entry, tarGz, zip } from "./archive.mjs";

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);

/**
 * §10.5's matrix. The payload is identical across all five: the plugin bundle
 * is prebuilt (§7.3) so the release carries no native code, and the CLI is
 * plain Node. The matrix is kept because it is the SELECTION contract — an
 * unlisted OS/arch fails with the list instead of downloading something that
 * will not run — and because an immutable release cannot gain an asset later.
 */
const platforms = [
  { name: "macos_arm64", format: "tar.gz" },
  { name: "macos_x86_64", format: "tar.gz" },
  { name: "linux_x86_64", format: "tar.gz" },
  { name: "linux_aarch64", format: "tar.gz" },
  { name: "windows_x86_64", format: "zip" },
];

const release = flag("--release");
if (
  release === undefined ||
  !/^v\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(release)
) {
  fail("--release vX.Y.Z is required. The asset is the version (§10.1).");
}
const outDir = path.resolve(flag("--out") ?? path.join(packageRoot, "release"));
const manifest = readJson(path.join(packageRoot, "package.json"));
const repository = manifest.repository.url
  .replace(/^git\+/, "")
  .replace(/^https:\/\/github\.com\//, "")
  .replace(/\.git$/, "");
const baseUrl =
  flag("--base-url") ??
  `https://github.com/${repository}/releases/download/${release}`;
// The staged payload carries the release identity; the working tree keeps
// saying `dev`, which is what it is. Both copies are replaced from one object,
// so the CLI and its skills can never disagree about which release they are —
// the skew §10.6 fails closed on is unreachable within a single asset.
const identity = {
  $comment: "Generated by scripts/release/stage.mjs. Do not edit.",
  release,
  sourceCommit: flag("--commit") ?? gitCommit(),
  packageVersion: manifest.version,
};
if (
  typeof identity.sourceCommit !== "string" ||
  !/^[a-f0-9]{40}$/.test(identity.sourceCommit)
)
  fail("A full source commit is required to stage a reviewed release");
const stampedIdentity = Buffer.from(`${JSON.stringify(identity, null, 2)}\n`);
const stampedPaths = new Set(["release.json", "skills/RELEASE.json"]);

// ---------- payload ----------
const payloadRoot = `ds-skills-${release}`;
const entries = [
  entry(`${payloadRoot}/bin/ds-skills`, read("installers/ds-skills"), true),
  entry(`${payloadRoot}/bin/ds-skills.cmd`, read("installers/ds-skills.cmd")),
];
// The shipped tree is package.json's `files` list, so a `files` omission is a
// release omission too rather than two lists that can disagree.
for (const item of [...manifest.files, "package.json"]) {
  for (const file of walk(path.join(packageRoot, item))) {
    const relative = path.relative(packageRoot, file).split(path.sep).join("/");
    entries.push(
      entry(
        `${payloadRoot}/lib/${relative}`,
        stampedPaths.has(relative) ? stampedIdentity : fs.readFileSync(file),
        relative === "bin/ds-skills.mjs",
      ),
    );
  }
}

// Seal each installed file before packaging. The reviewed pin binds the manifest
// digest, so editing both an installed file and its manifest cannot hide damage.
const payloadManifest = Buffer.from(
  `${JSON.stringify(
    {
      manifestVersion: "1",
      release,
      sourceCommit: identity.sourceCommit,
      files: Object.fromEntries(
        entries
          .map((file) => [
            file.name.slice(payloadRoot.length + 1),
            {
              sha256: sha256(file.bytes),
              executable: Boolean(file.mode & 0o111),
            },
          ])
          .sort(([a], [b]) => a.localeCompare(b)),
      ),
    },
    null,
    2,
  )}\n`,
);
entries.push(entry(`${payloadRoot}/payload-manifest.json`, payloadManifest));

prepareReleaseOutput(outDir, packageRoot);
fs.writeFileSync(path.join(outDir, "payload-manifest.json"), payloadManifest);

const assets = platforms.map((platform) => {
  const asset = `ds-skills-${release}-${platform.name}.${platform.format}`;
  const bytes = platform.format === "zip" ? zip(entries) : tarGz(entries);
  fs.writeFileSync(path.join(outDir, asset), bytes);
  return { platform: platform.name, asset, sha256: sha256(bytes) };
});

// ---------- SHA256SUMS ----------
const sumsAsset = "SHA256SUMS";
fs.writeFileSync(
  path.join(outDir, sumsAsset),
  `${assets.map((a) => `${a.sha256}  ${a.asset}`).join("\n")}\n`,
);

// ---------- bootstraps ----------
// The payload digests are baked into the bootstrap, so a verified bootstrap
// enforces payload integrity by itself (§10.3). A baked tag and asset name is
// selection identity; it is not integrity, and the two must not be confused.
const baked = {
  __DS_RELEASE__: release,
  __DS_REPOSITORY__: repository,
  __DS_SOURCE_COMMIT__: identity.sourceCommit ?? "",
  __DS_BASE_URL__: baseUrl,
  __DS_ASSETS__: assets
    .map((a) => `${a.platform}  ${a.asset}  ${a.sha256}`)
    .join("\n"),
  __DS_SUMS_ASSET__: sumsAsset,
  __DS_NODE_MINIMUM__: manifest.engines.node.replace(/[^0-9]/g, ""),
};

const bootstraps = ["install.sh", "install.ps1"].map((name) => {
  const bytes = Buffer.from(
    bake(read(`installers/${name}`).toString("utf8"), name),
  );
  fs.writeFileSync(path.join(outDir, name), bytes, { mode: 0o755 });
  return { asset: name, sha256: sha256(bytes) };
});

// ---------- the reviewed record ----------
// §10.4's shape, generated from the bytes staged above. The consumer commits
// this and verifies the bootstrap against it BEFORE executing it.
writeJson(path.join(outDir, "ds-skills.release.json"), {
  $comment:
    "Generated by scripts/release/stage.mjs from the staged bytes. Review, then commit to the consumer.",
  recordVersion: "2",
  repository,
  release,
  sourceCommit: identity.sourceCommit,
  payloadManifest: {
    asset: "payload-manifest.json",
    sha256: sha256(payloadManifest),
  },
  bootstrap: bootstraps[0],
  bootstrapPowershell: bootstraps[1],
  checksums: {
    asset: sumsAsset,
    sha256: sha256(read(path.join(outDir, sumsAsset))),
  },
  assets: Object.fromEntries(
    assets.map((a) => [a.platform, { asset: a.asset, sha256: a.sha256 }]),
  ),
});

process.stdout.write(
  `staged ${release} into ${path.relative(process.cwd(), outDir)}\n` +
    `${assets.map((a) => `  ${a.asset}  ${a.sha256.slice(0, 12)}…\n`).join("")}` +
    `${bootstraps.map((b) => `  ${b.asset}  ${b.sha256.slice(0, 12)}…\n`).join("")}`,
);

function bake(text, label) {
  let out = text;
  for (const [placeholder, value] of Object.entries(baked)) {
    if (!out.includes(placeholder)) {
      fail(
        `${label} has no ${placeholder}; the template and this script disagree.`,
      );
    }
    out = out.replaceAll(placeholder, value);
  }
  const leftover = /__DS_[A-Z0-9_]*__/.exec(out);
  if (leftover) fail(`${label} still contains ${leftover[0]} after baking.`);
  return out;
}

function walk(target) {
  if (!fs.existsSync(target))
    fail(`Declared release input is missing: ${target}`);
  if (fs.lstatSync(target).isSymbolicLink())
    fail(`Release source cannot be a symlink: ${target}`);
  if (fs.statSync(target).isFile()) return [target];
  return fs
    .readdirSync(target, { withFileTypes: true })
    .flatMap((e) => walk(path.join(target, e.name)));
}

function read(relative) {
  return fs.readFileSync(path.resolve(packageRoot, relative));
}
function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}
function writeJson(file, data) {
  fs.writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`);
}
function sha256(bytes) {
  return crypto.createHash("sha256").update(bytes).digest("hex");
}
function gitCommit() {
  try {
    return execFileSync("git", ["rev-parse", "HEAD"], {
      cwd: packageRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return null;
  }
}
function flag(name) {
  const index = process.argv.indexOf(name);
  return index === -1 ? undefined : process.argv[index + 1];
}
function fail(message) {
  process.stderr.write(`stage: ${message}\n`);
  process.exit(1);
}
