#!/usr/bin/env node
/**
 * Write the release identity the CLI and its skills both read.
 *
 * Run by `pnpm build`, so a built tree always carries one, and again by the
 * release staging script with the real tag. Two files rather than one, because
 * the whole point is that they can be separated: a consumer materializes the
 * skills somewhere of their own, and the copy has to carry its provenance with
 * it or skew is undetectable.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);

const manifest = JSON.parse(
  fs.readFileSync(path.join(packageRoot, "package.json"), "utf8"),
);

// `dev` is not a version — it is the absence of one, said out loud. A build
// that guessed `v0.4.0` from package.json would let an unstaged tree pass a
// check that exists to prove which release you are running.
const release = readFlag("--release") ?? "dev";
const sourceCommit = readFlag("--commit") ?? gitCommit();

const identity = {
  $comment:
    "Generated by scripts/stamp-release.mjs. Do not edit, and do not commit.",
  release,
  sourceCommit,
  packageVersion: manifest.version,
};

write(path.join(packageRoot, "release.json"), identity);
write(path.join(packageRoot, "skills", "RELEASE.json"), identity);
process.stdout.write(`stamped ${release} (${sourceCommit ?? "no commit"})\n`);

function write(file, data) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`);
}

function readFlag(flag) {
  const index = process.argv.indexOf(flag);
  return index === -1 ? undefined : process.argv[index + 1];
}

function gitCommit() {
  try {
    return execFileSync("git", ["rev-parse", "HEAD"], {
      cwd: packageRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    // A tarball unpacked outside a checkout has no git. That is not a failure.
    return null;
  }
}
