import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export function tokenProjectFixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "token-project-"));
  function write(file, data) {
    const target = path.join(root, file);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, `${JSON.stringify(data, null, 2)}\n`);
  }
  const config = {
    projectVersion: "1",
    tokens: {
      format: "family-files-v1",
      sourceDir: "design/source",
      recipesDir: "ui/recipes",
      extensionsNamespace: "dev.example.design",
      themes: { registry: "design/modes/list.json", directory: "design/modes" },
      figma: { excludedFamilies: ["private"] },
    },
  };
  const registry = {
    registryVersion: "1",
    defaultThemeId: "midnight",
    terminalFallbackThemeId: "midnight",
    unknownThemeIdBehavior: "error",
    themes: [
      { id: "midnight", file: "base.json", required: true, extends: null },
      {
        id: "daylight",
        file: "day.json",
        required: false,
        extends: "midnight",
      },
    ],
  };
  write("project.json", config);
  write("design/modes/list.json", registry);
  write("design/source/brand.tokens.json", {
    ink: { $type: "color", $value: "#102030" },
    text: { $type: "color", $value: "{brand.ink}" },
  });
  write("design/source/private.tokens.json", {
    gap: { $type: "dimension", $value: "8px" },
  });
  write("design/modes/base.json", {
    $extensions: { "dev.example.design": { themeId: "midnight" } },
  });
  write("design/modes/day.json", {
    $extensions: { "dev.example.design": { themeId: "daylight" } },
    brand: { ink: { $type: "color", $value: "#405060" } },
  });
  const recipe = {
    recipeVersion: "1",
    componentId: "notice",
    variantAxes: [{ name: "intent", values: ["normal"] }],
    defaults: { variants: { intent: "normal" }, state: "idle" },
    slots: { body: { color: "{brand.text}" } },
    states: { idle: { body: { color: "{brand.text}" } } },
    fallbacks: { missingVariantBehavior: "use-defaults", stateFallbacks: {} },
  };
  write("ui/recipes/notice.recipe.json", recipe);
  return {
    root,
    write,
    config,
    registry,
    recipe,
    configPath: path.join(root, "project.json"),
  };
}

export function tokenBuildFixture() {
  const f = tokenProjectFixture();
  f.config.tokens.build = {
    compiler: "tokens-studio-css-v1",
    banner: "Generated by example tokens. Do not edit.",
    formatting: {
      semi: true,
      singleQuote: true,
      tabWidth: 2,
      trailingComma: "es5",
      printWidth: 100,
    },
    runtime: {
      themeAttribute: "data-mode",
      identicalThemes: "error",
      compatibility: null,
    },
    outputs: {
      stagedCss: "build/source.css",
      runtimeCss: "ui/theme.css",
      typescript: "build/design.ts",
      figma: "build/figma.json",
    },
    lockPath: ".cache/tokens.lock",
  };
  f.write("project.json", f.config);
  return f;
}
